#!/usr/bin/env python3
"""
AttackGraphEngine: A Hierarchical Attack Representation Model (HARM) for IoMT Security.
This engine analyzes hospital network topologies, identifies potential attack paths to
critical medical devices (like infusion pumps), and calculates context-aware risk scores.
"""

import json
import networkx as nx

def get_risk_value(score_string):
    """
    Converts qualitative CVSS impact scores to quantitative values.
    
    Args:
        score_string (str): 'High', 'Medium', or 'Low'.
        
    Returns:
        int: Quantitative risk value (3, 2, or 1).
    """
    mapping = {"High": 3, "Medium": 2, "Low": 1}
    return mapping.get(score_string, 0)

class AttackGraphEngine:
    """
    The core logic engine for building attack graphs and recommending mitigations.
    """
    def __init__(self, vuln_data_path):
        """
        Initialize the engine with path to vulnerability library.
        """
        self.vuln_data_path = vuln_data_path
        self.vulnerabilities = {}
        self.network = nx.Graph()
        self.topology_name = "Default"
        
    def load_vulnerabilities(self):
        """
        Loads the JSON vulnerability library generated by vulnerability_builder.py.
        """
        try:
            with open(self.vuln_data_path, 'r') as f:
                self.vulnerabilities = json.load(f)
        except FileNotFoundError:
            print(f"[-] Error: Could not find {self.vuln_data_path}")

    def load_topology(self, topo_path):
        """
        Loads a network topology from a JSON file.
        
        Args:
            topo_path (str): Path to the topology JSON file.
        """
        try:
            with open(topo_path, 'r') as f:
                topo_data = json.load(f)
            
            # Reset network graph
            self.network = nx.Graph()
            self.topology_name = topo_data.get("name", "Unknown")
            
            # Add Nodes with metadata (Criticality and Exposure)
            for node in topo_data.get("nodes", []):
                self.network.add_node(node["id"], 
                                     profile=node["profile"],
                                     criticality=node.get("criticality", 1.0),
                                     exposure=node.get("exposure", 1.0))
            
            # Add Edges (Network reachability)
            for edge in topo_data.get("edges", []):
                self.network.add_edge(edge[0], edge[1])
            
        except FileNotFoundError:
            print(f"[-] Error: Could not find topology file {topo_path}")
        except json.JSONDecodeError:
            print(f"[-] Error: Failed to parse topology JSON at {topo_path}")

    def decorate_nodes(self, scoring_mode='new'):
        """
        Builds the Lower Layer of HARM (Vulnerabilities).
        Decorates each node with specific CVEs based on its device profile.
        
        Args:
            scoring_mode (str): 
                'new' -> Improved scoring (CVSS * Exploitability * Criticality * Exposure)
                'old' -> Legacy scoring (CVSS only)
        """
        for node, attr in self.network.nodes(data=True):
            profile = attr.get('profile')
            node_vulns = {}
            node_risk_score = 0
            
            criticality = attr.get('criticality', 1.0)
            exposure = attr.get('exposure', 1.0)
            
            # Match vulnerabilities from library to node profile
            for cve_id, cve_data in self.vulnerabilities.items():
                if cve_data['target_device'] == profile:
                    node_vulns[cve_id] = cve_data
                    
                    # Core NodeRisk formula
                    cvss = get_risk_value(cve_data['impact_score'])
                    
                    if scoring_mode == 'new':
                        # multiplier of 3 for easier exploits
                        exploitability = 3 if cve_data['exploit_complexity'] == 'Low' else 1
                        # NodeRisk = CVSS * Exploitability * Criticality * Exposure
                        vuln_risk = (cvss * exploitability * criticality * exposure)
                    else:
                        # Legacy mode ignores environment and safety context
                        vuln_risk = cvss
                        
                    node_risk_score += vuln_risk
            
            # Update the NetworkX node attributes
            self.network.nodes[node]['vulnerabilities'] = node_vulns
            self.network.nodes[node]['cumulative_risk'] = node_risk_score

    def patch_node(self, node_id):
        """
        Simulate patching all vulnerabilities on a specific node.
        Used for sensitivity analysis in the recommendation engine.
        """
        if node_id in self.network:
            self.network.nodes[node_id]['vulnerabilities'] = {}
            self.network.nodes[node_id]['cumulative_risk'] = 0

    def calculate_total_network_risk(self, target_node):
        """
        Calculates total aggregate risk based on all simple paths from attacker to target.
        """
        try:
            paths = list(nx.all_simple_paths(self.network, source='attacker', target=target_node))
            total_risk = 0
            for path in paths:
                path_risk = sum(self.network.nodes[node].get('cumulative_risk', 0) for node in path)
                total_risk += path_risk
            return total_risk
        except (nx.NetworkXNoPath, nx.NodeNotFound):
            return 0

    def calculate_highest_path_risk(self, target_node):
        """
        Identifies and returns the risk score of the most dangerous (highest risk) path.
        """
        try:
            paths = list(nx.all_simple_paths(self.network, source='attacker', target=target_node))
            max_risk = 0
            for path in paths:
                path_risk = sum(self.network.nodes[node].get('cumulative_risk', 0) for node in path)
                if path_risk > max_risk:
                    max_risk = path_risk
            return max_risk
        except (nx.NetworkXNoPath, nx.NodeNotFound):
            return 0

    def analyze_attack_paths(self, source, target):
        """
        Discovery engine: Finds and prints top attack paths to a target.
        """
        print(f"\n[*] Analyzing Attack Paths in '{self.topology_name}' from '{source}' to '{target}'...")
        
        if source not in self.network or target not in self.network:
            print(f"[-] Error: Source '{source}' or Target '{target}' not in network.")
            return

        try:
            paths = list(nx.all_simple_paths(self.network, source=source, target=target))
        except nx.NetworkXNoPath:
            paths = []
        
        path_metrics = []
        for path in paths:
            total_path_risk = 0
            exploited_cves = []
            
            for node in path:
                # Skip source and routing infra for exploit counts
                if node == source or self.network.nodes[node].get('profile') == 'Router': 
                    continue 
                
                total_path_risk += self.network.nodes[node].get('cumulative_risk', 0)
                vulns = self.network.nodes[node].get('vulnerabilities', {}).keys()
                if vulns:
                    exploited_cves.append(f"{node} ({','.join(vulns)})")
            
            path_metrics.append({
                'path': " -> ".join(path),
                'risk_score': total_path_risk,
                'exploits': exploited_cves
            })
            
        # Sort paths by risk score (descending)
        path_metrics.sort(key=lambda x: x['risk_score'], reverse=True)
        
        if not path_metrics:
            print("[-] No valid attack paths found.")
            return

        # Show top 5 most dangerous paths
        for i, pm in enumerate(path_metrics[:5]):
            print(f"\n--- Path {i+1} ---")
            print(f"Route: {pm['path']}")
            print(f"Path Risk Score: {pm['risk_score']:.2f}")
            print(f"Required Exploits: {pm['exploits']}")

    def generate_recommendations(self, target_node):
        """
        Mitigation Recommendation Engine.
        Simulates two scenarios: Patching Priority and Segmentation Blocking.
        """
        print(f"\n[*] Generating Mitigation Recommendations for target '{target_node}'...")
        
        base_risk = self.calculate_total_network_risk(target_node)
        if base_risk == 0:
            print("[+] Base network risk is 0. No recommendations needed.")
            return

        print("\n--- A. Patch Priority Recommendations ---")
        patch_impacts = []
        
        for node in list(self.network.nodes()):
            if node == 'attacker' or self.network.nodes[node].get('profile') == 'Router':
                continue
                
            original_vulns = self.network.nodes[node]['vulnerabilities']
            original_risk = self.network.nodes[node]['cumulative_risk']
            
            if not original_vulns:
                continue

            # Simulate patching the node
            self.patch_node(node)
            new_total_risk = self.calculate_total_network_risk(target_node)
            reduction = ((base_risk - new_total_risk) / base_risk) * 100
            
            if reduction > 0.01:
                patch_impacts.append((node, reduction))
            
            # Restore node to original vulnerable state
            self.network.nodes[node]['vulnerabilities'] = original_vulns
            self.network.nodes[node]['cumulative_risk'] = original_risk

        patch_impacts.sort(key=lambda x: x[1], reverse=True)
        for i, (node, red) in enumerate(patch_impacts[:5]):
            print(f"{i+1}. Patch {node} ({self.network.nodes[node]['profile']}) -> reduces risk {red:.1f}%")

        print("\n--- B. Segmentation Recommendations ---")
        edge_impacts = []
        edges = list(self.network.edges())
        base_paths_count = len(list(nx.all_simple_paths(self.network, source='attacker', target=target_node)))
        
        for u, v in edges:
            # Simulate blocking the connection
            self.network.remove_edge(u, v)
            
            try:
                new_total_risk = self.calculate_total_network_risk(target_node)
                new_paths = list(nx.all_simple_paths(self.network, source='attacker', target=target_node))
                new_paths_count = len(new_paths)
                reduction = ((base_risk - new_total_risk) / base_risk) * 100
                if reduction > 0.01 or new_paths_count < base_paths_count:
                    edge_impacts.append((u, v, reduction, new_paths_count))
            except (nx.NetworkXNoPath, nx.NodeNotFound):
                edge_impacts.append((u, v, 100.0, 0))
            
            # Restore the connection
            self.network.add_edge(u, v)

        edge_impacts.sort(key=lambda x: x[2], reverse=True)
        for i, (u, v, red, paths) in enumerate(edge_impacts[:5]):
            print(f"{i+1}. Block {u} <-> {v} reduces risk {red:.1f}% | Paths: {base_paths_count} -> {paths}")

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="Wireless Infusion Pump Attack Graph Engine")
    parser.add_argument("--topo", choices=["flat", "segmented"], default="segmented", help="Select topology")
    parser.add_argument("--target", default="pump_icu_1", help="Target node ID (e.g. pump_icu_1)")
    args = parser.parse_args()

    engine = AttackGraphEngine(vuln_data_path='data/vulnerability_library.json')
    engine.load_vulnerabilities()
    
    topo_file = f"topologies/{args.topo}.json"
    engine.load_topology(topo_file)
    engine.decorate_nodes()
    
    engine.analyze_attack_paths(source='attacker', target=args.target)
    engine.generate_recommendations(target_node=args.target)
